services:
  - type: web
    name: football-predictions-ai
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python run.py"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0